name: Flutter checks
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter create --platforms=android,linux .
      - run: rm -f test/widget_test.dart
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
